name: Trigger E2E execution
on:
  workflow_run:
    workflows:
      - merge
    types:
      - completed
jobs:
  trigger-e2e-workflow:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.PAT }} # Fine-grained GitHub PAT that was saved as repository secret
            script: |
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'son-la',
                  repo: 'snorlax-e2e',
                  workflow_id: 'e2e.yml',
                  ref: 'main'
              }).catch(error => error).then(response => {
                core.debug(response);
                if (response.status !== 204) {
                  core.setFailed(`create workflow_dispatch received status code ${response.status}`);
                }
              });